name: CI

on:
  push:
    branches:
      - develop
      - feature/*
  pull_request:
    branches:
      - main
      - develop

jobs:
  tests-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, sqlite3
          coverage: none

      - name: Cache Composer
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: |
          composer install --no-interaction --prefer-dist --no-progress

      - name: Prepare Environment for Tests
        run: |
          cp .env.example .env
          php -r "copy('database/database.sqlite', 'database/database.sqlite');" || true
          touch database/database.sqlite

      - name: Run Unit Tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: |
          vendor/bin/phpunit --testsuite Unit --colors=always

      - name: Code Style (Pint)
        run: |
          vendor/bin/pint --test

      - name: Validate Composer
        run: |
          composer validate --no-check-publish