name: Deploy to VPS

on:
  push:
    branches:
      - main  # branch principal do projeto

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          cat >>~/.ssh/config <<END
          Host vps
            HostName ${{ secrets.SSH_HOST }}
            User ${{ secrets.SSH_USER }}
            IdentityFile ~/.ssh/deploy_key
            StrictHostKeyChecking no
          END
      
      - name: Deploy para VPS
        run: |
          ssh vps 'cd /var/www/klgestorpub && \
          git pull origin main && \
          composer install && \
          php artisan migrate --force && \
          php artisan config:cache && \
          php artisan route:cache && \
          php artisan view:cache && \
          pm2 restart "php artisan serve --host=0.0.0.0 --port=8000" --name klgestorpub
          ' 