name: Deploy to VPS

on:
  push:
    branches:
      - main  # ou master, dependendo da sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          cat >>~/.ssh/config <<END
          Host vps
            HostName ${{ secrets.SSH_HOST }}
            User ${{ secrets.SSH_USER }}
            IdentityFile ~/.ssh/deploy_key
            StrictHostKeyChecking no
          END
      
      - name: Deploy para VPS
        run: |
          ssh vps 'cd /var/www/klgestorpub && \
          git pull origin main && \
          npm install && \
          npm run build && \
          pm2 restart klgestorpub
          ' 